FrontAsignacionActivoFijo/Models/ComponentesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using HtmlHelpers.BeginCollectionItem;

namespace FrontAsignacionActivoFijo.Models
{
    public class ComponentesViewModel
    {
        /// <summary>
        /// Obtiene o establece el id del componente
        /// </summary>
        public int IdComponente { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del componente
        /// </summary>
        [Display(Name = "Componente")]
        [Required(ErrorMessage = "Campo requerido")]
        public string Nombre { get; set; }

        /// <summary>
        /// Obtiene o establece la marca del componente
        /// </summary>
        [Required(ErrorMessage = "Campo requerido")]
        public string Marca { get; set; }

        /// <summary>
        /// Obtiene o establece el modelo del componente
        /// </summary>
        [Required(ErrorMessage = "Campo requerido")]
        public string Modelo { get; set; }

        /// <summary>
        /// Obtiene o establece la serie del componente
        /// </summary>
        [Display(Name = "No. Serie / Parte")]
        [Required(ErrorMessage = "Campo requerido")]
        public string Serie { get; set; }

        /// <summary>
        /// Obtiene o establece el procesador del componente
        /// </summary>
        [Required(ErrorMessage = "Campo requerido")]
        public string Procesador { get; set; }

        /// <summary>
        /// Obtiene o establece el disco duro del componente
        /// </summary>
        [Display(Name = "Disco duro")]
        [Required(ErrorMessage = "Campo requerido")]
        public string DiscoDuro { get; set; }

        /// <summary>
        /// Obtiene o establece la memoria ram del componente
        /// </summary>
        [Display(Name = "RAM")]
        [Required(ErrorMessage = "Campo requerido")]
        public string Ram { get; set; }

        /// <summary>
        /// Obtiene o establece las anotaciones 
        /// </summary>
        [Required(ErrorMessage = "Campo requerido")]
        public string Anotaciones { get; set; }

        /// <summary>
        /// Obtiene o establece el id del activo al cual se asigna el componente 
        /// </summary>    
        public int IdActivo { get; set; }


    }
}

FrontAsignacionActivoFijo/Controllers/ComponentesController.cs
using FrontAsignacionActivoFijo.Consumidor;
using FrontAsignacionActivoFijo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HtmlHelpers.BeginCollectionItem;

namespace FrontAsignacionActivoFijo.Controllers
{
    public class ComponentesController : Controller
    {


        private IConsumidorActivo _ServicioActivo;
        private IConsumidorCatalogos _ServicioCatalogos;
        private IConsuidorUbicaciones _ServicioUbicaciones;
        private IConsumidorComponentes _ServicioComponentes;
        private IConsumidorEmpleado _ServicioEmpleado;

        public ComponentesController() : this(new ConsumidorActivo(), new ConsumidorCatalogos(), new ConsumidorUbicaciones(), new ConsumidorComponentes(), new ConsumidorEmpleado())  { }

        public ComponentesController(IConsumidorActivo servicio, IConsumidorCatalogos servicio2, IConsuidorUbicaciones servicio3, IConsumidorComponentes servicio4, IConsumidorEmpleado servicio5)
        {
            this._ServicioActivo = servicio;
            this._ServicioCatalogos = servicio2;
            this._ServicioUbicaciones = servicio3;
            this._ServicioComponentes = servicio4;
            this._ServicioEmpleado = servicio5;
        }



        // GET: Componentes
        
        public async Task<ActionResult> Index()
        {
            List<CatalogosViewModel> ListaEmpresas = new List<CatalogosViewModel>();
            ListaEmpresas.Add(new CatalogosViewModel() { Id = 1, Nombre = "SERVICIOS INTEGRALES S.A" });
            ListaEmpresas.Add(new CatalogosViewModel() { Id = 2, Nombre = "NEOTEC" });

            ViewBag.ListaEmpresas = ListaEmpresas;
            ViewBag.ListaUbicaciones = await _ServicioUbicaciones.ObtenerUbicaciones(2);
            
            return View(new List<ActivoViewModel>());
        }

        public async Task<JsonResult> MostrarActivos(string Empresa, int UbicacionId)
        {
            return Json(await _ServicioActivo.ObtenerActivosEmpresaUbicac(Empresa, UbicacionId), JsonRequestBehavior.AllowGet);
        }


        public ActionResult AgregandoComponente()        {
           

            return PartialView("_Componente");

        }


      


        public ActionResult AgregarComponentes(string SS, int ActivoId)
        {

            ViewBag.SActivo = SS;
            ViewBag.IdDelActivo = ActivoId;

            return View();
        }

   
        [HttpPost]
        public async Task<ActionResult> AgregarComponentes(GuardarComponentesViewModel Lista)
        {

            KeyValuePair<int, string> respuesta = new KeyValuePair<int, string>();

            

            foreach (var i in Lista.ListaComponentes)
            {
                i.IdActivo = Lista.IdActivo;
                respuesta  = await _ServicioComponentes.GuardarListaComponentes(i);
            }
                                

            if (respuesta.Value.Contains("Operacion Exitosa"))
            {
                TempData["Mensaje"] = new KeyValuePair<string, string>("success", "Los componentes se han registrado correctamente!!!");
                              
            }

            return RedirectToAction("Index");
        }


        public async Task<ActionResult> VerComponentes(int ActivoID)
        {
            var ActivoEncontrado = await _ServicioActivo.ObtenerActivoPorId(ActivoID);

            var NombreEmpleado = await _ServicioEmpleado.ObtenerEmpleado(ActivoEncontrado.NumEmpleado);

            ViewBag.SerieEnc = ActivoEncontrado.SerieImei;
            ViewBag.MarcaEnc = ActivoEncontrado.Marca;
            ViewBag.ModeloEnc = ActivoEncontrado.ModeloVersion;
            ViewBag.ProcesadorEnc = ActivoEncontrado.ProcesadorSim;
            ViewBag.DiscoEnc = ActivoEncontrado.DiscoDuroPlan;
            ViewBag.RamEnc = ActivoEncontrado.RamLinea;
            ViewBag.AsignadoEnc = NombreEmpleado.Nombre;
            ViewBag.ArticuloEnc = ActivoEncontrado.NombreArticulo;

            var ListaDeComponentesRepo = await _ServicioComponentes.ObtenerComponentesPorId(ActivoID);        

            return View(ListaDeComponentesRepo);
        }

    }

   
}

FrontAsignacionActivoFijo/Views/Componentes/AgregarComponentes.cshtml
@model FrontAsignacionActivoFijo.Models.GuardarComponentesViewModel

@using (Html.BeginForm("AgregarComponentes","Componentes", FormMethod.Post, new { @id = "FrmDatosComponentes" }))
{
    <div class="row"><label>&nbsp; </label></div>
    <div class="row"><label>&nbsp; </label></div>
    <div class="row"><label>&nbsp; </label></div>

    <div class="container">


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <div class="row">
            <div class="form-group col-md-2">
                @Html.Label("N° Serie / IMEI", htmlAttributes: new { @class = "control-label" })

                @Html.Editor("SActivo", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
            </div>



            <div class="form-group col-md-2 hide">

                @Html.EditorFor(model => model.IdActivo, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.IdDelActivo } })

            </div>


            <div class="form-group col-md-2 pull-right">
                @*<input type="button" id="BtnAgregar" value="Agregar" class="btn-info form-control col-md-2" />*@
                <button type="button" class="btn-info form-control col-md-2" id="BtnAgregar">
                    <i class="glyphicon glyphicon-plus"></i>  Agregar
                </button>
            </div>

        </div>



        <div class="row col-md-12" id="DivSeccionesComponentes">




            @Html.Partial("_Componente")



        </div>



        <div class="row"><label>&nbsp; </label></div>

        <div class="row"><label>&nbsp; </label></div>


        <div class="row">

            <div class="row"><label>&nbsp; </label></div>

            <div class="col-md-offset-3 col-md-10">
                <div class="row col-md-2">   </div>

                <div class="row col-md-8">
                    @*<input type="submit" value="Guardar" class="btn btn-success col-md-5" id="BtnGuardarComponentes" />*@
                    <button type="submit" class="btn btn-success col-md-5" id="BtnGuardarComponentes">
                        <i class="glyphicon glyphicon-floppy-disk"></i> &nbsp;&nbsp;  Guardar
                    </button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 pull-right">
                @*<input type="button" value="Regresar" class="btn btn-danger" onclick=" />*@
                @Html.ActionLink("Cancelar", "Index", "Componentes", new { @class = "btn btn-danger" })
            </div>
        </div>

    </div>

}



@section Scripts
    {

    @Scripts.Render("~/bundles/jqueryval")


    <script type="text/javascript">


            $('#BtnAgregar').click(function () {

              
                $.post('/Componentes/AgregandoComponente',
                    function (partialView) {
                        $('#DivSeccionesComponentes').append(partialView);
                        $("#FrmDatosComponentes").removeData('validator');
                        $("#FrmDatosComponentes").removeData('unobtrusiveValidation');
                        $.validator.unobtrusive.parse($("#FrmDatosComponentes"));
                    },
                    "html"
                );
            });
        
    </script>

    <script src="~/Scripts/JSComponentes.js"></script>
}

FrontAsignacionActivoFijo/Views/Componentes/Index.cshtml
@model IEnumerable<FrontAsignacionActivoFijo.Models.ActivoViewModel>

@{
    ViewBag.Title = "Componentes";
}




<h2 style="text-align:center">Agregar Componentes</h2>
<div class="row"><label>&nbsp; </label></div>

<div class="row">

    <div class="form-group col-md-3">
        @Html.Label("Empresa", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownList("SelectEmpresa", new SelectList(ViewBag.ListaEmpresas, "Id", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

    </div>

    <div class="form-group col-md-3">
        @Html.Label("Ubicación", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownList("SelectUbicacion", new SelectList(ViewBag.ListaUbicaciones, "Id", "Nombre"), "Selecciona una opción", new { @class = "form-control" })

    </div>



</div>

<div class="row"><label>&nbsp; </label></div>
<h2>Activos</h2>
<div class="row"><label>&nbsp; </label></div>
<table class="table" id="TablaActivosComponentes">
    <thead>
        <tr>
            <th>
                N° Serie
            </th>
            <th>
                Clasificación
            </th>
            <th>
                Artículo
            </th>
            <th>
                Marca
            </th>
            <th>
                Modelo
            </th>
            <th>
                Procesador
            </th>
            <th>
                HDD
            </th>
            <th>
                RAM/Telefono
            </th>
            <th>
                Agregar
            </th>
            <th>
                Ver
            </th>

        </tr>
    </thead>

    <tbody>

      

    </tbody>


</table>



<div class="modal" tabindex="-1" role="dialog" id="ModalAgrearComponentes" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Agregar Componentes</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="ContenidoAgregarComponentes">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    <script src="~/Scripts/JSComponentes.js"></script>

}

FrontAsignacionActivoFijo/Views/Componentes/VerComponentes.cshtml
@model IEnumerable<FrontAsignacionActivoFijo.Models.ComponentesViewModel>

@{
    ViewBag.Title = "Ver Componentes";
}

   
<h2 style="text-align:center">Ver Componentes</h2>
<div class="row"><label>&nbsp; </label></div>

<div class="row">
    <div class="form-group col-md-3">
        @Html.Label("N° Serie / IMEI", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("SerieEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("Marca", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("MarcaEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("Modelo", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("ModeloEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("Procesador / SIM", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("ProcesadorEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>


</div>

<div class="row">

    <div class="form-group col-md-3">
        @Html.Label("Disco duro / Plan", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("DiscoEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("RAM / Linea", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("RamEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("Asignado", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("AsignadoEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

    <div class="form-group col-md-3">
        @Html.Label("Articulo", htmlAttributes: new { @class = "control-label" })

        @Html.Editor("ArticuloEnc", new { htmlAttributes = new { @class = "form-control col-md-2", @disabled = "disabled" } })
    </div>

</div>

<div class="row"><label>&nbsp; </label></div>
<div class="row"><label>&nbsp; </label></div>
<div class="row">
    <div class="col-md-2"><label>&nbsp; </label></div>

    <div class="col-md-8">

        <table class="table" id="TablaComponentesAgregados">
            <thead>
                <tr>

                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Serie)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Marca)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Modelo)
                    </th>
                </tr>



            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Serie)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Marca)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Modelo)
                        </td>

                    </tr>
                }

            </tbody>


        </table>


    </div>

    <div class="col-md-2"><label>&nbsp; </label></div>
</div>

<div class="row"><label>&nbsp; </label></div>
<div class="row">
    <div class="col-md-12 pull-right">
        @*<input type="button" value="Regresar" class="btn btn-danger" onclick=" />*@
        @Html.ActionLink("Regresar", "Index", "Componentes", new { @class = "btn btn-danger" })
    </div>
</div>


@section Scripts {

    <script src="~/Scripts/JSComponentes.js"></script>

}

FrontAsignacionActivoFijo/Views/Componentes/_Componente.cshtml
@model  FrontAsignacionActivoFijo.Models.ComponentesViewModel

@using (Html.BeginCollectionItem("ListaComponentes"))
{

    <div class="ItemComponente  col-md-12">
        <div class="row"><label>&nbsp; </label></div>

        <fieldset class="col-md-12" style=" border: 1px solid gray; border-radius: 15px">
            @*<legend>Componente</legend>*@

            <div class="row col-md-2 pull-right">

                <div class="form-group col-md-1 pull-right">

                    <a href="#" class="BorraElemento" style="border-radius: 100%; color: red; font-size:30px; text-decoration:none">X</a>

                </div>
            </div>

            <div class="row col-md-12">

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })

                </div>

            </div>


            <div class="row col-md-12">

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Procesador, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Procesador, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Procesador, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.DiscoDuro, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.DiscoDuro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiscoDuro, "", new { @class = "text-danger" })

                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.Ram, htmlAttributes: new { @class = "control-label" })

                    @Html.EditorFor(model => model.Ram, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ram, "", new { @class = "text-danger" })

                </div>

            </div>


            <div class="row col-md-12">


                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Anotaciones, htmlAttributes: new { @class = "control-label" })

                    @Html.TextAreaFor(model => model.Anotaciones, new { @class = "form-control ", @cols = 30, @rows = 3 })
                    @Html.ValidationMessageFor(model => model.Anotaciones, "", new { @class = "text-danger" })

                </div>


            </div>

            <div class="row"><label>&nbsp; </label></div>

            <div class="row"><label>&nbsp; </label></div>

        </fieldset>

    </div>

}